### ISSUE TITLE
Proposition of improvement: add Feature Dataset

### ISSUE THREAD

**Issue by pvernier** [Guts/DicoGIS#2]
Not an issue, rather a proposition of improvement for a future release. 
In a case of a ESRI geodatabase, I think it would be really useful to have a column in the Excel file for the feature dataset. Like that it would be easier to look for a particular feature class and to filter the Exel file.

**Comment by Guts** [comment]
Not accepted by GDAL / OGR team, so for now, the re is no way to achieve it.
