### ISSUE TITLE
Import Error: cannot import name get_column_letter

### ISSUE THREAD

**Issue by Guts** [Guts/DicoGIS#22]
cf. https://github.com/Guts/DicoGIS/issues/7#issuecomment-256903786

Changes in openpyxl.
Use openpyxl =< 2.3.5 in the meanwhile.

**Comment by bobo-romania** [comment]
Hi, 
I still have a bug with the 2.3.0 version of openpyxl
![a](https://cloud.githubusercontent.com/assets/3932557/19810096/5c285240-9d2c-11e6-9ae3-745daeececdf.png)
