### ISSUE TITLE
 UnicodeDecodeError

### ISSUE THREAD

**Issue by errazkisibawaih** [Guts/DicoGIS#26]
Hello,

I have some encoding problem on my postgreSQL database and when I try to have excel file of all my tables I have this issue.
" Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyo", line 1532, in __call__
  File "DicoGIS.py", line 493, in <lambda>
  File "DicoGIS.py", line 907, in process
  File "DicoGIS.py", line 1489, in check_fields
  File "DicoGIS.py", line 1548, in test_connection
  File "DicoGIS.py", line 1420, in process_db
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 28: ordinal not in range(128) "

Please notice that all tables names don't have special characters and they are in lowercase.

**Comment by Guts** [comment]
@errazkisibawaih please, could send me (by email):

* DB connection parameters (read mode only preferred), so I'll be able to reproduce this issue. 
* log file (LOG_DicoGIS.log)
* options.ini file

**Comment by errazkisibawaih** [comment]
I found the origin of the issue. Indeed when a table name have an accent or
a special character, we have the issue of  "UNICODE".

You have to put the whole script in UTF8 I suppose.

Best wishes,

ER-RAZKI Sibawaih

**Comment by Guts** [comment]
Ok, cool. So you can close this issue please :)

**Comment by errazkisibawaih** [comment]
Done ;)
