### ISSUE TITLE
Problème d'ouverture du fichier xls

### ISSUE THREAD

**Issue by mfangain** [Guts/DicoGIS#28]
Le traitement se fait bien, sans erreur, l'outil affiche bien les fichiers trouvés.

Dans le log, pas d'erreur non plus.
[LOG_DicoGIS.log](https://github.com/Guts/DicoGIS/files/1390559/LOG_DicoGIS.log)

Je ne sais pas pour quelles raisons le fichier a réussi à s'ouvrir 2 ou 3 fois.
J'ai essayé d'ouvrir excel (2010) avant ou après avoir lancé le traitement, a priori cela ne vient pas de là.

Merci!

MFANGAIN

**Comment by Guts** [comment]
Merci de prendre le temps de faire un retour.
Pouvez-vous joindre également le fichier Excel en question svp ? (pensez à filtrer les éventuelles informations confidentielles avt)

**Comment by mfangain** [comment]
Y a-t-il un répertoire par défaut où le fichier est généré?
A la fin du traitement, Excel ne se lance pas et je n'ai pas d'aperçu du fichier, et donc pas la fenêtre d'enregistrement.
En fait, j'ai l'impression qu'il n'est pas généré du tout ce fichier excel...

MFANGAIN

**Comment by Guts** [comment]
Mauvaise manip ?

**Comment by mfangain** [comment]
Ah oui, pardon, je ne connais pas trop le fonctionnement de Github...

**Comment by Guts** [comment]
Pas de souci, chaque outil demande à être pris en main :)

Dans le log, j'ai l'impression que vous ne cliquez pas systématiquement sur le bouton Lancer, si ?
Désolé si je donne l'impression de répondre bêtement mais pouvez-vous me confirmer que vous suivez ce process :

1. lancer DicoGIS.exe
2. cliquer sur `Parcourir`
3. sélectionner le dossier où sont les données
4. ne cocher que les formats souhaités et "raisonnables" (éviter sur des milliers de dalles rasters ou de PDF par exemple)
5. cliquer sur `Lancer` 
-----

Note pour plus tard : par ailleurs, d'après le log, il y a aussi plusieurs problèmes avec l'installation de GDAL sur le système visiblement inaccessible. Mais ça n'a a priori aucun impact sur votre problème :

```
2017-10-09 08:59:33,526 || ERROR || DicoGIS || Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
```

**Comment by mfangain** [comment]
En fait, je n'ai pas le temps de cliquer sur Lancer.
 Voici les étapes que je suis : 
1. Lancement de DicoGIS.exe
2. Sélection des formats souhaités
3. Clic sur Parcourir
4. Sélection du répertoire voulu.
5. clic sur ok
Le traitement se lance alors automatiquement, avant que j'ai pu cliquer sur le bouton Lancer.
J'obtiens alors la fenêtre que j'ai posté sur forumSIG.

J'ai essayé de cliquer après ça sur Lancer, mais le traitement s'arrête systématiquement sur un fichier et ne va pas jusqu'au bout.

Je vais pousser un peu plus mes tests, pour savoir si en fait ce ne serait pas un fichier particulier qui poserait souci...


Une petite précision sur mon installation : 
Mes logiciels SIG sont installés sur un serveur auquel j'accède par une connexion en bureau à distance, mais excel n'est pas installé sur ce serveur (libre office si). 
Sur mon poste, aucun SIG n'est installé, mais j'ai excel : je lance donc dicogis depuis mon poste.
J'ai essayé depuis le serveur directement, mais je n'ai pas de résultat plus concluant...

**Comment by Guts** [comment]
> clic sur ok
> Le traitement se lance alors automatiquement, avant que j'ai pu cliquer sur le bouton Lancer.

Ce n'est pas le traitement qui se lance automatiquement mais le listing, l'étape qui explore l'arborescence de fichiers que vous avez sélectionnée via le bouton parcourir. Comme dans le GIF ci-dessous (ancienne version mais ça ne change rien sur le principe) :

![](https://raw.githubusercontent.com/Guts/DicoGIS/master/doc/02_DicoGIS_Listing.gif)

C'est cette étape qui remplit le nombre de fichiers par formats dans la fenêtre de progression, comme dans votre capture sur ForumSIG :

![dicoplus_fin_traitement](https://user-images.githubusercontent.com/1596222/31731905-e11038ac-b436-11e7-9413-23aef3000e94.JPG)

C'est ensuite qu'il faut faire les étapes :

> 4. ne cocher que les formats souhaités et "raisonnables" (éviter sur des milliers de dalles rasters ou de PDF par exemple)
> 5. cliquer sur `Lancer` 

**Est-ce que vous êtes bien arrivée jusque là ?**

> Je vais pousser un peu plus mes tests, pour savoir si en fait ce ne serait pas un fichier particulier qui poserait souci...

Vous pouvez essayer avec [la précédente version](https://github.com/Guts/DicoGIS/releases/download/v2.1.0-beta3/DicoGIS_2.1.0-beta3.zip).

> Une petite précision sur mon installation :
> Mes logiciels SIG sont installés sur un serveur auquel j'accède par une connexion en bureau à distance, mais excel n'est pas installé sur ce serveur (libre office si).
> Sur mon poste, aucun SIG n'est installé, mais j'ai excel : je lance donc dicogis depuis mon poste.
> J'ai essayé depuis le serveur directement, mais je n'ai pas de résultat plus concluant...

Merci pour ces infos. L'installation d'un SIG ou d'Excel n'est pas requise sur l'ordinateur exécutant DicoGIS. Par exemple, je l'utilise sur une clé USB en général ;)

**Comment by mfangain** [comment]
Bonjour,

J'ai trouvé d'où venait le souci.
Le traitement semblait s'arrêter sur le même fichier à chaque fois : c'était le fichier INSEE des données carroyées. Je l'ai isolé, le traitement a pu finir et le fichier xls s'est bien généré.
J'ai relancé le traitement sur le répertoire où j'avais isolé le fichier, et en fait, le traitement est allé jusqu'au bout, après un certain temps.
J'avais pourtant essayé de laisser tourner longtemps, mais visiblement pas suffisamment...

Je vais faire un retour sur le forumSIG.

Je m'excuse pour le dérangement, et merci beaucoup pour votre support!

MFANGAIN

**Comment by Guts** [comment]
Bonjour,

En voilà une fin heureuse :)
Désolé pour les performances, qui ne sont pas dans les prétentions de l'outil. Pour le carroyage de l'INSEE, peut-être y'a t'il des optimisations à faire sur la donnée (index spatial par exemple) ?
Pouvez-vous me la faire parvenir que je l'ajoute à mon jeu de données tests svp ? peut-être trouverais-je une idée pour améliorer les perfs ? :)

Merci à vous pour votre ténacité !
Je vous laisse fermer votre ticket.

**Comment by mfangain** [comment]
Pour les données, le zip fait près de 80Mo. Je vous l'envoie par Wetransfer :
https://we.tl/h7UjQtfN7K

Pour ma part, je vais le supprimer, car c'est le fichier de la France entière, et je travaille à l'échelle d'une intercommunalité, et en plus j'utilise QGIS et le fichier TAB ne m'est plus utile.
Pour moi, les performances de l'outil sont suffisantes, il suffit juste de savoir attendre ;-) Il m'a fait gagner beaucoup de temps à côté de ce problème!

Bonne fin de semaine!

MFANGAIN

**Comment by Guts** [comment]
Merci pour le lien. Je viens de le supprimer de votre commentaire après usage pour plus de confidentialité :).

Merci également pour les retours et surtout, bonne fin de semaine !
Julien
