### ISSUE TITLE
Problème à l'installation sur linux (ubuntu 14.04)

### ISSUE THREAD

**Issue by bobo-plateau** [Guts/DicoGIS#7]
Salut, 
je rencontre un problème à l'installation. celui ci n'est pas directement relié à DicoGIS mais cela risque d'affecter tes utilisateurs sur une base ubuntu 14.04.

Le problème se situe à l'installation de GDAL.
voici mon message d'erreur 

`Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-STHdsI/gdal/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-wXAmyF-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-STHdsI/gdal`

J'ai trouvé une ressource en applicant la bonne vielle méthode du Copié/Collé sur toutes solutions proposées (je ne maitrise pas bien virtualenv). Je n'ai pas trouvé de solution.

Voilà, peut être qu'il y a un hack à trouver pour esquiver ce problème mais ce n'est pas dans mes compétences.
Je te laisse le choix de considérer comme relevant de dicoGis ou pas.

Bonne journée 

Bobo

**Comment by Guts** [comment]
En effet, ça sent un problème de compilation dans l'environnement virtuel. Je teste aussi rapidement sur Ubuntu mais c'ets vrai que c'est parfois capricieux, selon les compilateurs installés ou pas, etc.

D'après ce que j'ai pu lire, ce n'est pas un problème isolé mais d'emplacement des en-têtes de compilation de GDAL. D'ailleurs, il y a carrément un module Python dédié : https://pypi.python.org/pypi/pygdal/1.11.1.1

Essaye :

```bash
sudo apt-get install libgdal-dev
export CPLUS_INCLUDE_PATH=/usr/include/gdal
export C_INCLUDE_PATH=/usr/include/gdal
source virtenv/bin/activate
pip install --no-install GDAL
python setup.py build_ext --include-dirs=/usr/include/gdal
pip install --no-download GDAL
```

**Comment by Guts** [comment]
Une petite mise à jour svp ?

**Comment by bobo-romania** [comment]
Bonjour,
désolé pour le temps de réponse. Le contexte évolue de mon côté puisque qu'il y a une montée de version (vers 16.04). Je rencontre un autre soucis, non pas à l'installation mais  à l'éxecution. voici la procédure:
Je suis les différentes étapes indiquées dans le readme.
je l'ance `python DicoGIS.py`
et je retrouve le problème suivant 
![screenshot at 2016-10-28 13 55 37](https://cloud.githubusercontent.com/assets/3932557/19805883/571a7c98-9d17-11e6-8c2e-e8b1604bc584.png)

Voilà, si cela peut t'apporter de l'eau au moulin.
Je n'ai plus de machine sous 14.04 pour faire le test mais je me dis qu'il est plus pertinent de travailler sur la 16.04 dans la mesure ou elle sera maintenue jusqu'en 2021 et est stable à ce jour.

Bon courage

**Comment by Guts** [comment]
Pas de souci, je suis loin d'être un modèle de réactivité sur ce projet (quoique là pour le coup, je performe !).
Je connais ce bug, c'est lié à des changements assez importants dans openpyxl. Je fais une autre issue.

Du coup, puis-je en conclure que l'installation fonctionne sur la 16.04 ?

**Comment by Guts** [comment]
Est-ce qu'avec les nouvelles instructions, l'installation fonctionne ?
cf. https://github.com/Guts/DicoGIS/commit/e421114e0f7a117a0a31aae57057f4d80540715b

**Comment by bobo-romania** [comment]
Salut, depuis la mise à jour, cela fonctionne bien. J'ai juste l'impression que dès qu'il faut chercher dans des sous-fichiers, cela mouline en continue. Donc j'assemble tout dans un même dossier.
Merci

**Comment by Guts** [comment]
> Salut, depuis la mise à jour, cela fonctionne bien.
En voilà une bonne nouvelle :) !

> J'ai juste l'impression que dès qu'il faut chercher dans des sous-fichiers, cela mouline en continue. Donc j'assemble tout dans un même dossier.

Peux-tu joindre le fichier log stp ?

**Comment by Guts** [comment]
Pas de nouvelles, bonnes nouvelles.
